// Photographs shown inside the wardrobe. Generated by tools/gallery/build-manifest.mjs.
window.GALLERY = {
  "categories": [
    {
      "id": "candlelit",
      "title": "Candlelit & Gothic"
    },
    {
      "id": "coquette",
      "title": "Lace & Coquette"
    },
    {
      "id": "y2k",
      "title": "Y2K & Pop"
    },
    {
      "id": "love",
      "title": "Love Stories"
    },
    {
      "id": "grads",
      "title": "Grads"
    },
    {
      "id": "costume",
      "title": "Costumes & Cosplay"
    }
  ],
  "photos": [
    {
      "src": "img/gallery/candlelit/6579CEAA-9A7D-4087-A044-D366C77302F5.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in white sits in a tree raising a glinting sword.",
      "thumb": "img/gallery/candlelit/thumbs/6579CEAA-9A7D-4087-A044-D366C77302F5.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_1319.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Woman with long black hair frames her face with dark-nailed hands.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_1319.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_1450.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Hands with long dark nails cradle a bright starburst of light.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_1450.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_2063.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Woman in a white lace veil holds a sword and a flame in a dark wood.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_2063.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_2087.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in a white veil sits in the woods holding a sword upright.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_2087.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_2187.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Person in a yellow tunic holds a glowing sword up to their face.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_2187.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_2598.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in a white dress reaches toward a lantern in a dark garden.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_2598.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_2668.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman framed inside a wooden doorway filled with smoke and candlelight.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_2668.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3242.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Woman in black lace at a red table spread with candles and old books.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3242.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3249.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Two red-haired women share a secret over a red tablecloth set with teacups.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3249.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3309.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Three women in dark lace at a candlelit red tea table.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3309.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3334.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Red-haired woman at a gothic tea party, a candle and teacups in front of her.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3334.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3545.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in a gold satin gown at a red-draped table lit by candles and pearls.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3545.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3673.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Two friends in black leather sit against a wall in a shaft of light.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3673.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3695.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Woman in gold satin reclines on a red velvet set among candlesticks.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3695.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_3820.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in a gold dress kneels on red velvet beneath gold number balloons.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_3820.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6016.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Client portrait paired with Mel's review: a woman in a leather jacket holds a guitar across her shoulders.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6016.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6064.webp",
      "w": 1051,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman in a black leather jacket plays an electric guitar in stage smoke.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6064.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6241.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Leopard-print heels, a guitar, a skull and a candle on a dark set.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6241.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6332.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman with dark bangs and red lips plays a cream guitar close to the lens.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6332.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6352.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Legs in leopard heels up in the air beside an electric guitar.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6352.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_6754.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Woman with black lipstick reclines on a floral bed holding a candle, a brass candelabra lit behind her against red velvet.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_6754.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_7042.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Candlelit close portrait of a woman with dark bangs beside a brass candelabra.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_7042.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_8577.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Person in black and white corpse paint in a dark room.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_8577.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_8630.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Person in corpse paint at a keyboard in the dark.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_8630.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_9388.webp",
      "w": 1067,
      "h": 1600,
      "category": "candlelit",
      "alt": "Black and white portrait of a woman in a bra, hugging her knees in shadow.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_9388.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_9590.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Person with green-tinted bangs reclines on red fabric in a black mesh top.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_9590.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_9596.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "Person with green-tinted bangs reclines on red velvet, looking upward.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_9596.webp"
    },
    {
      "src": "img/gallery/candlelit/IMG_9675.webp",
      "w": 1600,
      "h": 1067,
      "category": "candlelit",
      "alt": "A silhouette in profile against glowing blue fabric, cords hanging overhead.",
      "thumb": "img/gallery/candlelit/thumbs/IMG_9675.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_0363.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Blonde woman in a white dress sits beside a large white dollhouse in a garden.",
      "thumb": "img/gallery/coquette/thumbs/IMG_0363.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_0383.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Blonde woman rests her chin on the roof of a dollhouse, under trees.",
      "thumb": "img/gallery/coquette/thumbs/IMG_0383.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_0505.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Blonde woman in a lace shawl stands in sunlight beneath a tree.",
      "thumb": "img/gallery/coquette/thumbs/IMG_0505.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1485.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a pink corset dress holds two lit candles in a glass holder.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1485.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1728.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a pale green slip dress among sunlit leaves.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1728.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1733.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a long blue cape and flower crown stands in a sunny clearing.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1733.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1736.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman with a blue cape and hair bow looks back over her shoulder among trees.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1736.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1759.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a pale blue slip dress holds blue flowers against a tree trunk.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1759.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_1802.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Woman in a pale blue dress reclines in the grass with a blue fan.",
      "thumb": "img/gallery/coquette/thumbs/IMG_1802.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_2323.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman with white feathered wings stands beneath a ring light that glows like a halo.",
      "thumb": "img/gallery/coquette/thumbs/IMG_2323.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_2683.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Woman in a white lace dress sits in a garden with a lace parasol over her face.",
      "thumb": "img/gallery/coquette/thumbs/IMG_2683.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4461.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Woman in a white bonnet among white sheets drying on a line.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4461.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4490.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a white dress and bonnet holds a basket among hanging laundry.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4490.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4683.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Woman rests her chin on a fence rail, white sheets behind her.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4683.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4747.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "White dress, knee socks and boots beside a basket of apples in the grass.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4747.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4785.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Woman in a white dress lies in the grass, arms overhead.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4785.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_4857.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a white ruffled dress twirls on the grass.",
      "thumb": "img/gallery/coquette/thumbs/IMG_4857.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_5637.webp",
      "w": 1600,
      "h": 1067,
      "category": "coquette",
      "alt": "Red-haired woman sits in the grass under trees.",
      "thumb": "img/gallery/coquette/thumbs/IMG_5637.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_7022.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in white sits in a sunlit field by a pond.",
      "thumb": "img/gallery/coquette/thumbs/IMG_7022.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_7854.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a cream lace gown reclines on dark rocks by the sea at dusk, a lace-draped figure beside her.",
      "thumb": "img/gallery/coquette/thumbs/IMG_7854.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_7977.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Red-haired woman in a white lace veil and wings kneels in a field under power lines.",
      "thumb": "img/gallery/coquette/thumbs/IMG_7977.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_7978.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in lace wings and veil kneels in grass at sunset, power lines behind.",
      "thumb": "img/gallery/coquette/thumbs/IMG_7978.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_7984.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a white lace veil and feathered wings kneels in sunlit grass.",
      "thumb": "img/gallery/coquette/thumbs/IMG_7984.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_8014.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in white with lace wings walks down a road at dusk under power lines.",
      "thumb": "img/gallery/coquette/thumbs/IMG_8014.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_8034.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "Woman in a white lace veil and feathered wings at sunset.",
      "thumb": "img/gallery/coquette/thumbs/IMG_8034.webp"
    },
    {
      "src": "img/gallery/coquette/IMG_8200.webp",
      "w": 1067,
      "h": 1600,
      "category": "coquette",
      "alt": "A woman in a floral lace dress reflected in an ornate oval mirror, candles at the side.",
      "thumb": "img/gallery/coquette/thumbs/IMG_8200.webp"
    },
    {
      "src": "img/gallery/y2k/AB188D71-4CE1-46DE-977D-D15DF64B7CCE.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Two friends in swimsuits on a jet ski, a rainbow overhead.",
      "thumb": "img/gallery/y2k/thumbs/AB188D71-4CE1-46DE-977D-D15DF64B7CCE.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_0179.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Two friends lie head to head on a patterned blanket.",
      "thumb": "img/gallery/y2k/thumbs/IMG_0179.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_0349.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Two friends in swimsuits lounge on a blanket at the beach.",
      "thumb": "img/gallery/y2k/thumbs/IMG_0349.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_0662.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Two friends in swimsuits sit by the water making a heart with their hands.",
      "thumb": "img/gallery/y2k/thumbs/IMG_0662.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_1676.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Woman in a red jacket and plaid skirt kneels on the sand at sunset.",
      "thumb": "img/gallery/y2k/thumbs/IMG_1676.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_1698.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a red jacket and plaid skirt stands in the surf as the sun sets.",
      "thumb": "img/gallery/y2k/thumbs/IMG_1698.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_1726.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a plaid skirt and knee socks poses on a rock at golden hour, laptop in hand.",
      "thumb": "img/gallery/y2k/thumbs/IMG_1726.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2200.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "A woman cuts another woman's long hair against a pink backdrop.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2200.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2230.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Chunky black platform shoe with scissors against pink.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2230.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2263.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "A ringed hand dangles silver scissors against pink.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2263.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2793.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Woman in a black dress lies across a pool table holding a cue, balls scattered around her.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2793.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2817.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Two women in black dresses and heels lie on a pool table with their legs in the air.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2817.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_2827.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Two women in fur coats sit on a pool table, looking back over bare shoulders.",
      "thumb": "img/gallery/y2k/thumbs/IMG_2827.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3537.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Hands with pink nails hold a disco ball against pink hair.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3537.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3548.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman with pink hair lies upside down on pink fabric, hands at her face.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3548.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3614.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Woman with pink hair against a pink backdrop, a disco ball overhead.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3614.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3620.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Close portrait of a woman with pink hair and decorated nails against a purple wall and disco ball.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3620.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3622.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman with pink hair and long nails covers part of her face, pink light behind.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3622.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3788.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in camo and a crop top poses on an old artillery gun.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3788.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3803.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Close on a camo skirt and a toy grenade at the hip.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3803.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_3934.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in camo leans against the barrel of an old cannon at a fort.",
      "thumb": "img/gallery/y2k/thumbs/IMG_3934.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_4676.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Woman in red tights kicks a leg up beside a laundromat cart full of red clothes.",
      "thumb": "img/gallery/y2k/thumbs/IMG_4676.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_4714.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in red tights sits in a laundromat cart, fisheye lens, washers all around.",
      "thumb": "img/gallery/y2k/thumbs/IMG_4714.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_4721.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Fisheye view of a woman in red tights and zebra heels lounging in a laundromat cart.",
      "thumb": "img/gallery/y2k/thumbs/IMG_4721.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_4901-B.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in red tights curled inside a round laundromat washer, fisheye lens.",
      "thumb": "img/gallery/y2k/thumbs/IMG_4901-B.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_4901.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Fisheye view of a woman in red tights sitting inside a laundromat washer.",
      "thumb": "img/gallery/y2k/thumbs/IMG_4901.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_5099.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a red top and fishnets leans into a stacked laundromat washer.",
      "thumb": "img/gallery/y2k/thumbs/IMG_5099.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_5769.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "A costumed figure in red and pink stands in a round spotlight against a brick wall.",
      "thumb": "img/gallery/y2k/thumbs/IMG_5769.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_6101.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman with teal and black hair in a pearl necklace, a pink lens flare across her face.",
      "thumb": "img/gallery/y2k/thumbs/IMG_6101.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_6120.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman with teal and black hair hides behind a giant swirl lollipop.",
      "thumb": "img/gallery/y2k/thumbs/IMG_6120.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_6310.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "A cue lines up a rack of pool balls on green felt.",
      "thumb": "img/gallery/y2k/thumbs/IMG_6310.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_6508.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman with a tattooed arm leans on a pool table, chin on her hand.",
      "thumb": "img/gallery/y2k/thumbs/IMG_6508.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_7293.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a black slip dress and boots outside a pink motel at night.",
      "thumb": "img/gallery/y2k/thumbs/IMG_7293.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_8737.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Blonde woman in a grey sweater sits on stacked books in a bookshop.",
      "thumb": "img/gallery/y2k/thumbs/IMG_8737.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_8765.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Blonde woman in a grey sweater leans on a bookshelf holding books.",
      "thumb": "img/gallery/y2k/thumbs/IMG_8765.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_8779.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Blonde woman with books in front of tall shelves, eyes closed.",
      "thumb": "img/gallery/y2k/thumbs/IMG_8779.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_8780.webp",
      "w": 1600,
      "h": 1067,
      "category": "y2k",
      "alt": "Blonde woman hugs a stack of books against the shelves.",
      "thumb": "img/gallery/y2k/thumbs/IMG_8780.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_9598.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a gold bikini stands in the sea against the setting sun.",
      "thumb": "img/gallery/y2k/thumbs/IMG_9598.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_9603.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Silhouette of a woman with her hands in her hair against a low sun over the water.",
      "thumb": "img/gallery/y2k/thumbs/IMG_9603.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_9616.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Woman in a gold bikini sits in the shallows at sunset.",
      "thumb": "img/gallery/y2k/thumbs/IMG_9616.webp"
    },
    {
      "src": "img/gallery/y2k/IMG_9626.webp",
      "w": 1067,
      "h": 1600,
      "category": "y2k",
      "alt": "Silhouette of a woman wading into a golden sea at sunset.",
      "thumb": "img/gallery/y2k/thumbs/IMG_9626.webp"
    },
    {
      "src": "img/gallery/love/IMG_0907.webp",
      "w": 1600,
      "h": 1067,
      "category": "love",
      "alt": "Two hands meet over coffee cups, seen through a rain-streaked window.",
      "thumb": "img/gallery/love/thumbs/IMG_0907.webp"
    },
    {
      "src": "img/gallery/love/IMG_0913.webp",
      "w": 1600,
      "h": 1067,
      "category": "love",
      "alt": "A couple kisses at a rainy diner window.",
      "thumb": "img/gallery/love/thumbs/IMG_0913.webp"
    },
    {
      "src": "img/gallery/love/IMG_0967.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple talks under the bright lights of a late-night shop front.",
      "thumb": "img/gallery/love/thumbs/IMG_0967.webp"
    },
    {
      "src": "img/gallery/love/IMG_1310.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple dances on the shore at sunset.",
      "thumb": "img/gallery/love/thumbs/IMG_1310.webp"
    },
    {
      "src": "img/gallery/love/IMG_3390.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A bride and groom kiss under mossy oaks.",
      "thumb": "img/gallery/love/thumbs/IMG_3390.webp"
    },
    {
      "src": "img/gallery/love/IMG_3652.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Wedding guests raise glasses of champagne in a toast.",
      "thumb": "img/gallery/love/thumbs/IMG_3652.webp"
    },
    {
      "src": "img/gallery/love/IMG_3709.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Close on a lace wedding gown, a tattoo across her chest and his hands at her waist.",
      "thumb": "img/gallery/love/thumbs/IMG_3709.webp"
    },
    {
      "src": "img/gallery/love/IMG_4195.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Wedding rings resting in red flowers and baby's breath.",
      "thumb": "img/gallery/love/thumbs/IMG_4195.webp"
    },
    {
      "src": "img/gallery/love/IMG_4432.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Two people lie head to head on a floral quilt, photographed from above.",
      "thumb": "img/gallery/love/thumbs/IMG_4432.webp"
    },
    {
      "src": "img/gallery/love/IMG_4883-B.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple in white holds each other close under sunlit trees.",
      "thumb": "img/gallery/love/thumbs/IMG_4883-B.webp"
    },
    {
      "src": "img/gallery/love/IMG_4883.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A bride in a full white gown and a man in white face each other in golden light.",
      "thumb": "img/gallery/love/thumbs/IMG_4883.webp"
    },
    {
      "src": "img/gallery/love/IMG_4907.webp",
      "w": 1600,
      "h": 1067,
      "category": "love",
      "alt": "Two hands reach for each other against green leaves.",
      "thumb": "img/gallery/love/thumbs/IMG_4907.webp"
    },
    {
      "src": "img/gallery/love/IMG_4945.webp",
      "w": 1600,
      "h": 1067,
      "category": "love",
      "alt": "A couple in white lies in the grass, faces close together.",
      "thumb": "img/gallery/love/thumbs/IMG_4945.webp"
    },
    {
      "src": "img/gallery/love/IMG_4961.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Two hands with rings clasped above a white sleeve on the grass.",
      "thumb": "img/gallery/love/thumbs/IMG_4961.webp"
    },
    {
      "src": "img/gallery/love/IMG_5814.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple embraces in a sunny meadow, one lifting a foot.",
      "thumb": "img/gallery/love/thumbs/IMG_5814.webp"
    },
    {
      "src": "img/gallery/love/IMG_5826.webp",
      "w": 1600,
      "h": 1067,
      "category": "love",
      "alt": "A couple sits together on a low wall in warm evening light.",
      "thumb": "img/gallery/love/thumbs/IMG_5826.webp"
    },
    {
      "src": "img/gallery/love/IMG_5865.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Two silhouettes lean in for a kiss against bright leaves.",
      "thumb": "img/gallery/love/thumbs/IMG_5865.webp"
    },
    {
      "src": "img/gallery/love/IMG_5896.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple rests against a tree in the late sun, one asleep on the other's lap.",
      "thumb": "img/gallery/love/thumbs/IMG_5896.webp"
    },
    {
      "src": "img/gallery/love/IMG_6012.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple lies in the grass in dappled sunlight.",
      "thumb": "img/gallery/love/thumbs/IMG_6012.webp"
    },
    {
      "src": "img/gallery/love/IMG_7504.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Two people sit against a tree with a cat in a harness between them.",
      "thumb": "img/gallery/love/thumbs/IMG_7504.webp"
    },
    {
      "src": "img/gallery/love/IMG_9442.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Two people share a close portrait against a red curtain, one hand resting on the other's face.",
      "thumb": "img/gallery/love/thumbs/IMG_9442.webp"
    },
    {
      "src": "img/gallery/love/IMG_9774.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple in white embraces under green trees.",
      "thumb": "img/gallery/love/thumbs/IMG_9774.webp"
    },
    {
      "src": "img/gallery/love/IMG_9842.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "Client portrait paired with Bradyn and Carter's review: a couple sits together under a sunlit tree.",
      "thumb": "img/gallery/love/thumbs/IMG_9842.webp"
    },
    {
      "src": "img/gallery/love/IMG_9853.webp",
      "w": 1067,
      "h": 1600,
      "category": "love",
      "alt": "A couple walks hand in hand across a sunny park.",
      "thumb": "img/gallery/love/thumbs/IMG_9853.webp"
    },
    {
      "src": "img/gallery/grads/IMG_0567.webp",
      "w": 1600,
      "h": 1067,
      "category": "grads",
      "alt": "Client portrait paired with Riley's review: a graduate in a black gown reaches toward purple flowers.",
      "thumb": "img/gallery/grads/thumbs/IMG_0567.webp"
    },
    {
      "src": "img/gallery/grads/IMG_0687.webp",
      "w": 1600,
      "h": 1067,
      "category": "grads",
      "alt": "Graduate in a stole lies on the grass, cap on her chest.",
      "thumb": "img/gallery/grads/thumbs/IMG_0687.webp"
    },
    {
      "src": "img/gallery/grads/IMG_2636.webp",
      "w": 1600,
      "h": 1067,
      "category": "grads",
      "alt": "Person in a record store holds a Descendents album in front of their face.",
      "thumb": "img/gallery/grads/thumbs/IMG_2636.webp"
    },
    {
      "src": "img/gallery/grads/IMG_5676.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Red-haired graduate in black among green leaves.",
      "thumb": "img/gallery/grads/thumbs/IMG_5676.webp"
    },
    {
      "src": "img/gallery/grads/IMG_5721.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Red-haired graduate holds up a white tassel to the camera.",
      "thumb": "img/gallery/grads/thumbs/IMG_5721.webp"
    },
    {
      "src": "img/gallery/grads/IMG_6503.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Graduate in a black gown and yellow stole sits on stone steps.",
      "thumb": "img/gallery/grads/thumbs/IMG_6503.webp"
    },
    {
      "src": "img/gallery/grads/IMG_6605.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Graduate in a yellow stole looks over her shoulder among green leaves.",
      "thumb": "img/gallery/grads/thumbs/IMG_6605.webp"
    },
    {
      "src": "img/gallery/grads/IMG_6741.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Graduate in a black gown and yellow stole stands on a porch.",
      "thumb": "img/gallery/grads/thumbs/IMG_6741.webp"
    },
    {
      "src": "img/gallery/grads/IMG_6802.webp",
      "w": 1067,
      "h": 1600,
      "category": "grads",
      "alt": "Graduate in a black dress holds a blue mortarboard over their face in front of a sticker-covered door.",
      "thumb": "img/gallery/grads/thumbs/IMG_6802.webp"
    },
    {
      "src": "img/gallery/costume/IMG_0182.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Cosplayer with long teal pigtails reaches toward the camera in blue light.",
      "thumb": "img/gallery/costume/thumbs/IMG_0182.webp"
    },
    {
      "src": "img/gallery/costume/IMG_0207.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Cosplayer with teal pigtails sits on a bed among speakers and fabric, lit blue.",
      "thumb": "img/gallery/costume/thumbs/IMG_0207.webp"
    },
    {
      "src": "img/gallery/costume/IMG_0288.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Silhouette of a figure with long pigtails against a glowing blue circle.",
      "thumb": "img/gallery/costume/thumbs/IMG_0288.webp"
    },
    {
      "src": "img/gallery/costume/IMG_0344.webp",
      "w": 1600,
      "h": 1067,
      "category": "costume",
      "alt": "Hands on a laptop keyboard bathed in teal light, seen from above.",
      "thumb": "img/gallery/costume/thumbs/IMG_0344.webp"
    },
    {
      "src": "img/gallery/costume/IMG_5095.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Woman in a white tutu and knee socks holds a red balloon in front of a graffiti wall at night.",
      "thumb": "img/gallery/costume/thumbs/IMG_5095.webp"
    },
    {
      "src": "img/gallery/costume/IMG_5105.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Woman in a white ruffled costume with red pom-poms peeks around a graffiti-covered wall.",
      "thumb": "img/gallery/costume/thumbs/IMG_5105.webp"
    },
    {
      "src": "img/gallery/costume/IMG_5139.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Woman in a white tutu clambers over concrete under red light.",
      "thumb": "img/gallery/costume/thumbs/IMG_5139.webp"
    },
    {
      "src": "img/gallery/costume/IMG_5205.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "Close on white tutu, lace socks and black boots beside red balloons.",
      "thumb": "img/gallery/costume/thumbs/IMG_5205.webp"
    },
    {
      "src": "img/gallery/costume/IMG_5220.webp",
      "w": 1067,
      "h": 1600,
      "category": "costume",
      "alt": "White tutu and lace gloves against dry grass at night, a scrape on one knee.",
      "thumb": "img/gallery/costume/thumbs/IMG_5220.webp"
    }
  ]
};
